### ISSUE TITLE
`pulumi up` Command Fails with ConcurrentUpdateError and Exit Code 255

### ISSUE THREAD

**Issue by dirien** [pulumi/actions#1034]
### What happened?

When I run a `pulumi up` I get following error message:

```bash
warning: A new version of Pulumi is available. To upgrade from version '3.90.1' to '3.91.1', visit https://pulumi.com/docs/install/ for manual instructions and release notes.
Pulumi version 3.90.1 is already installed on this machine. Skipping download
Logging into the Pulumi Cloud backend.
pulumi up on dev
  Updating (dev)
  
  
  
  /home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:74
                  ? new ConcurrentUpdateError(result)
  ^
  ConcurrentUpdateError: code: -2
   stdout: 
   stderr: Command failed with exit code [25](https://github.com/dirien/pulumi-github/actions/runs/6703109171/job/18213280949#step:5:26)5: pulumi up --yes --skip-preview --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --stack dev --non-interactive
  error: [409] Conflict: Another update is currently in progress.
  To learn more about possible reasons and resolution, visit https://www.pulumi.com/docs/troubleshooting/#conflict
  Updating (dev)
  
   err?: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --stack dev --non-interactive
  error: [[40](https://github.com/dirien/pulumi-github/actions/runs/6703109171/job/18213280949#step:5:41)9] Conflict: Another update is currently in progress.
  To learn more about possible reasons and resolution, visit https://www.pulumi.com/docs/troubleshooting/#conflict
  Updating (dev)
  
  
      at Object.createCommandError (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:74:1)
      at Object.<anonymous> (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:76:1)
      at Generator.throw (<anonymous>)
      at rejected (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:19:1)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

When run locally on my machine, everything works fine. What is strange is that, the resource were created in that run, when I check the Pulumi Cloud:
![image](https://github.com/pulumi/actions/assets/38325136/b47ae86f-7817-4bc6-86ca-ff78871dff25)

### Example

```bash
Run pulumi/actions@v4
  with:
    command: up
    stack-name: dev
    github-token: ***
    pulumi-version: ^[3](https://github.com/dirien/pulumi-github/actions/runs/6703109171/job/18213280949#step:5:3)
    work-dir: ./
    comment-on-pr: false
    comment-on-summary: false
    expect-no-changes: false
    diff: false
    target-dependents: false
    refresh: false
    upsert: false
    remove: false
    edit-pr-comment: true
    color: auto
    exclude-protected: false
  env:
    PULUMI_ACCESS_TOKEN: ***
```

### Output of `pulumi about`

Pulumi: v3.90.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@dirien, from the screenshot it looks like you're using Deployments? Are you using both Deployments and the action? This could explain the concurrent update... Deployments is running the update, as well as an update running in GitHub actions via the action.

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll assume the issue is not relevant anymore and will close it.
