### ISSUE TITLE
`pulumi preview` is ignoring `secret-provider` parameter

### ISSUE THREAD

**Issue by pcyang** [pulumi/actions#1170]
### What happened?

I followed the instruction in the Readme and passed in my gcpkms `secret-provider`, but I'm still getting error that ask me for `PULUMI_CONFIG_PASSPHRASE` or `PULUMI_CONFIG_PASSPHRASE_FILE`
https://github.com/pulumi/actions?tab=readme-ov-file#configuration

My example github action step is in the example section below.

Here's the full debug error:
```
##[debug]Evaluating condition for step: 'Preview infrastructure changes 📋'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Preview infrastructure changes 📋
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run pulumi/actions@v4
##[debug]Configuration is loaded
##[debug]Platform: linux-x64
Configured range: ^3
/usr/local/bin/pulumi version
v3.116.0
warning: A new version of Pulumi is available. To upgrade from version '3.116.0' to '3.116.1', visit https://pulumi.com/docs/install/ for manual instructions and release notes.
Pulumi version 3.116.0 is already installed on this machine. Skipping download
Logging into gs://MY_GCP_PULUMI_STATE_BUCKET
##[debug]Working directory resolved at /home/runner/work/MY_REPO/MY_REPO
::group::pulumi preview on MY_STACK_NAME
pulumi preview on MY_STACK_NAME
  ##[debug]Running action preview
  /home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77
                      : new CommandError(result);
  ^
  CommandError: code: -2
   stdout: 
   stderr: Command failed with exit code 255: pulumi preview --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --event-log /tmp/automation-logs-preview-IgkP4w/eventlog.txt --stack MY_STACK_NAME --non-interactive
  error: getting stack configuration: get stack secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
   err?: Error: Command failed with exit code 255: pulumi preview --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --event-log /tmp/automation-logs-preview-IgkP4w/eventlog.txt --stack MY_STACK_NAME --non-interactive
  error: getting stack configuration: get stack secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
      at Object.createCommandError (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77:1)
      at Object.<anonymous> (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:76:1)
      at Generator.throw (<anonymous>)
      at rejected (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:19:1)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Preview infrastructure changes 📋
```

Am I passing it incorrectly? how do I get `pulumi preview` command to use my custom secret-provider?

### Example

```
      - name: Preview infrastructure changes 📋
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: MY_STACK_NAME
          cloud-url: gs://MY_GCP_PULUMI_STATE_BUCKET
          secrets-provider: gcpkms://projects/MY_PROJECT/locations/MY_REGION/keyRings/MY_KEY_RINGS/cryptoKeys/MY_KEY
```

### Output of `pulumi about`

Cannot do pulumi about in github action.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pcyang** [comment]
Adding more context -- `Pulumi.MY_STACK_NAME.yaml` is not checked in to my repository. Locally, I need to do `pulumi config refresh` before I run the `pulumi preview` command. It seems like I'd need way to be able to do that in pulumi action.

**Comment by pcyang** [comment]
Okay, looks like I can just do a `pulumi config refresh` right before it as a workaround for now

```
      - name: Pulling remote config for Pulumi 🛠️
        run: |
          pulumi stack select MY_STACK_NAME
          pulumi config refresh

      - name: Preview infrastructure changes summary 📋
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: MY_STACK_NAME
          cloud-url: gs://MY_GCP_PULUMI_STATE_BUCKET
```

**Comment by justinvp** [comment]
@pcyang, out of curiosity, why aren't you checking in `Pulumi.MY_STACK_NAME.yaml`?

The `secrets-provider` option primarily exists for use with the `upsert` option (see https://github.com/pulumi/actions/issues/338):

> `upsert` - (optional) Allows the creation of the specified stack if it
  currently doesn't exist. **PLEASE NOTE:** This will create a
  `Pulumi.<stack-name>.yaml` file that you will need to add back to source
  control as part of the action if you wish to perform any further tasks with
  that stack.

**Comment by bradyburke** [comment]
Ran into this as well. Exactly how @pcyang mentioned it - although different languages
