### ISSUE TITLE
actions@v3 doesn't appear to work well with `pipenv`

### ISSUE THREAD

**Issue by parkedwards** [pulumi/actions#516]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hello - we're trying to implement the `pulumi/actions@v3` step for the first time in our workflow

We currently use `pipenv` (eg. project has a `Pipfile.lock`) to lock dependencies for ci/cd.  Previously, we pulled in the `pulumi` CLI via `pulumi/setup-pulumi@v2` + invoked our preview/up steps like so:

```yaml
      - name: Pipenv install
        id: pipenv-install
        run: pipenv install

      - name: Pulumi Preview
        run: pipenv run pulumi --cwd my-pulumi-project preview -s stack-name --logtostderr
```

^ note the `pipenv run` invocation

However, we thought to just drop in this new into into our GHA workflow YAML as-is, but we're seeing what looks like an virtual environment conflict - specifically, the action can't find the `pulumi` dependency installed:

```
      pulumi:pulumi:Stack tracing-dev  Traceback (most recent call last):
      pulumi:pulumi:Stack tracing-dev    File "/home/actions/actions-runner/_work/_tool/pulumi/3.24.1/x64/pulumi-language-python-exec", line 14, in <module>
      pulumi:pulumi:Stack tracing-dev      import pulumi
      pulumi:pulumi:Stack tracing-dev  ModuleNotFoundError: No module named 'pulumi'
      pulumi:pulumi:Stack tracing-dev  It looks like the Pulumi SDK has not been installed. Have you run pip install?
      pulumi:pulumi:Stack tracing-dev  If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
      pulumi:pulumi:Stack tracing-dev  error: an unhandled error occurred: Program exited with non-zero exit code: 1
      pulumi:pulumi:Stack tracing-dev  1 error; 6 messages
   
  Diagnostics:
    pulumi:pulumi:Stack (tracing-dev):
      Traceback (most recent call last):
        File "/home/actions/actions-runner/_work/_tool/pulumi/3.24.1/x64/pulumi-language-python-exec", line 14, in <module>
          import pulumi
      ModuleNotFoundError: No module named 'pulumi'
      It looks like the Pulumi SDK has not been installed. Have you run pip install?
      If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
   
      error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

I know that the pulumi project configuration can take a `virtualenv` configuration, but that seemed to only be for `venv` and not `pipenv`.  Are there any known issues around this action + `pipenv` specifically?

### Steps to reproduce

1. Python Pulumi project, with subdirectories (each subdir has a Pulumi project that we navigate via the `work-dir` config
2. managed by `pipenv`, so there should be a `Pipfile.lock`
3. Dropping in the `pulumi/actions@v3` action, after a pipenv install step
4.

Expected: 
I expected the `preview` command to work as though it could navigate to the `pulumi` dependency in the `pipenv` context

Actual: 
Cannot find the `pulumi` module

**Comment by parkedwards** [comment]
to add a little more context ( i apologize for the truncated output pastes, there's some stuff here I'm attempting to redact )

this is the setup log output for the action itself; note the "successfully deleted pre-existing" pulumi bin message

```
Run pulumi/actions@v3.15.0
Configured range: ^3
Matched version: v3.24.1
Install destination is /home/actions/.pulumi
Successfully deleted pre-existing /home/actions/.pulumi/bin
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/actions/.pulumi -f /home/actions/actions-runner/_work/_temp/e[22](https://github.com/blockfi/zeus/runs/5150207556?check_suite_focus=true#step:22:22)b89f3-3d35-4351-9875-b1cb8[23](https://github.com/blockfi/zeus/runs/5150207556?check_suite_focus=true#step:22:23)b6eed
```

**Comment by parkedwards** [comment]
any possible updates on this one?

**Comment by RobbieMcKinstry** [comment]
Hey @parkedwards , sorry for the slow reply on this.

Am I understanding your issue correctly?
Previously, you ran `pulumi/setup-pulumi@v2` to install the Pulumi CLI. Then, you could run it from within the context of `pipenv` like this:

```yml
- name: Pulumi Preview
   run: pipenv run pulumi --cwd my-pulumi-project preview -s stack-name --logtostderr
```

Now, however, with `v3`, there is no more `setup` action that installs the binary in the `$PATH`. Since your previous workflow required wrapping `pulumi` invocations with `pipenv run` (so you could source a project-specific Python SDK), the Action is no longer able to find a copy of the SKD (since it has been localized to a project subdirectory via pipenv).

That's my summary of your issue. Please correct me if I'm wrong! 

> Are there any known issues around this action + pipenv specifically?

Not that I'm aware of specific to pipenv, but I recently read a similar issue. I believe in https://github.com/pulumi/actions/issues/554 this user wants to do something similar, executing the `pulumi` binary from a wrapper process so they can use Yarn PnP (which I'm unfamiliar with).

> 1. Python Pulumi project, with subdirectories (each subdir has a Pulumi project that we navigate via the work-dir config

Is it necessary for reproduction that there be multiple subdirectories? From reading the issue, it appears the problem would be reproducible with a single repo installing the Pulumi SDK using `pipenv`.

One last question:

> this is the setup log output for the action itself;

What do you mean by "setup log" here? Are you indicating that's the log from running:

```yml
- name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: stack-name
          work-dir: my-pulumi-project
          comment-on-pr: true
        env:
          PULUMI_ACCESS_TOKEN: "${{ secrets.PULUMI_TOKEN }}"
```

Since there's no longer a `setup` action in v3, I imagine you're not referring to a specific GH Action step prior to the above?

I can try to reproduce some time this week. Apologies again for the delay.

**Comment by RobbieMcKinstry** [comment]
@parkedwards Hi again! I'm still doing some digging on this.

In your original code snippet...

```yml
      - name: Pipenv install
        id: pipenv-install
        run: pipenv install

      - name: Pulumi Preview
        run: pipenv run pulumi --cwd my-pulumi-project preview -s stack-name --logtostderr
```

...the `pulumi` CLI is running as a subprocess of `pipenv`, which is how `pulumi` can find the Pulumi SDK. Right now when that happens you typically have to use `[pulumi/pulumi-setup](https://github.com/marketplace/actions/setup-pulumi)` to install the CLI into PATH.

However, I'm seeing that muuuch earlier versions of the action supported `pipenv` as first-class. This [commit](https://github.com/pulumi/actions/commit/ba58c77ae0471c1f154bd36645e61d9657222565) introduced support (I found [this related PR](https://github.com/pulumi/pulumi/pull/6019) as well). However, these changes looked to be for the old, Docker-based version of this action. I'm unsure if the TS version of the action ever had `pipenv` support.

This all leads me to believe the issue you're seeing doesn't have to do with the monorepo layout, but `pipenv` support more directly.
